"""Breed Priority — re-exports for backwards compatibility.

All constants have moved to focused submodules:
  scoring.py  — weights, tiers, trait ratings, thresholds
  theme.py    — colors, chip pairs, heatmap colors
  styles.py   — Qt stylesheet strings
  columns.py  — column layout, data roles, room style, injury names
"""

# noqa: F401 — everything here is intentionally re-exported

from .collapsible_splitter import LEFT_PANEL_W, CollapseSplitter

from .scoring import (
    TRAIT_LOW_THRESHOLD, TRAIT_HIGH_THRESHOLD,
    BREED_PRIORITY_WEIGHTS, WEIGHT_UI_ROWS, SCORE_COLUMNS,
    BREED_PRIORITY_TIERS,
    TRAIT_RATING_OPTIONS, TRAIT_RATING_LABELS, TRAIT_RATING_VALUES,
    RATING_SHORT_LABELS,
)

from .theme import (
    CLR_TOP_PRIORITY, CLR_DESIRABLE, CLR_NEUTRAL, CLR_UNDECIDED, CLR_UNDESIRABLE,
    RATING_ITEM_COLORS,
    CLR_STATE_SELECTED_BG, CLR_STATE_SELECTED_FG, CLR_STATE_SELECTED_BORDER,
    CLR_STATE_SUBDUED_FG, CLR_STATE_SUBDUED_BG,
    CLR_STATE_SUBDUED_HOVER_FG, CLR_STATE_SUBDUED_HOVER_BG,
    CLR_LABEL_SUBDUED,
    _SEL_BG, _SEL_FG, _SEL_BORDER,
    _DIM_FG, _DIM_BG, _DIM_HOVER_FG, _DIM_HOVER_BG, _DIM_LABEL_FG,
    _THEME_DARK, _CLR_RED, _CLR_YELLOW,
    CLR_TEXT_CONTENT_PRIMARY, CLR_TEXT_CONTENT_SECONDARY,
    CLR_TEXT_LABEL_UI, CLR_TEXT_LABEL_GROUP, CLR_TEXT_LABEL_SUBGROUP, CLR_TEXT_LABEL_COUNT,
    CLR_TEXT_CONTENT_UNSCORED, CLR_TEXT_CONTENT_MUTED,
    CLR_TEXT_PRIMARY, CLR_TEXT_SECONDARY, CLR_TEXT_UI_LABEL,
    CLR_TEXT_GROUP, CLR_TEXT_SUBLABEL, CLR_TEXT_COUNT,
    CLR_TEXT_GRAYEDOUT, CLR_TEXT_MUTED,
    CLR_SURFACE_APP_MAIN, CLR_SURFACE_APP_ALT, CLR_SURFACE_SCORE_AREA, CLR_SURFACE_PANEL,
    CLR_SURFACE_HEADER, CLR_SURFACE_HEADER_BORDER, CLR_SURFACE_DEEP,
    CLR_SURFACE_NEUTRAL_OVERLAY,
    CLR_BG_MAIN, CLR_BG_ALT, CLR_BG_SCORE_AREA, CLR_BG_PANEL,
    CLR_BG_HEADER, CLR_BG_HEADER_BDR, CLR_BG_DEEP,
    _NEUTRAL_SURFACE, CLR_SURFACE_NEUTRAL, CLR_SURFACE_SEPARATOR,
    CLR_GENDER_MALE, CLR_GENDER_FEMALE, CLR_GENDER_UNKNOWN,
    _CHIP_GENDER_MALE, _CHIP_GENDER_FEMALE, _CHIP_GENDER_UNKNOWN,
    CLR_INTERACTIVE, CLR_INTERACTIVE_BG, CLR_INTERACTIVE_BDR, CLR_INTERACTIVE_HOV,
    CLR_HIGHLIGHT,
    CLR_VALUE_POS, CLR_VALUE_POS_BG, CLR_VALUE_NEG, CLR_VALUE_NEG_BG,
    CLR_VALUE_NEUTRAL, _CLR_AGE_OLD,
    _SEX_EMOJI_GAY, _SEX_EMOJI_BI,
    _CHIP_H, _CHIP_PAD_X, _CHIP_GAP, _CHIP_RADIUS,
    _CHIP_TOP_PRIORITY, _CHIP_DESIRABLE, _CHIP_UNDESIRABLE,
    _CHIP_NEUTRAL, _CHIP_UNDECIDED,
    _CHIP_LOVE, _CHIP_HATE,
    _CHIP_LOVE_OUTLINE, _CHIP_HATE_OUTLINE,
    _CHIP_AGGRO_HI, _CHIP_AGGRO_LO,
    _CHIP_AGE_WARN, _CHIP_DIM,
    _CHIP_NEUTRAL_STABLE, _CHIP_NEUTRAL_FAINT,
    _CHIP_OVERFLOW_LOVE, _CHIP_OVERFLOW_HATE,
    _SEP_BAND_BG, _HEAT_POS, _HEAT_NEG,
)

from .styles import (
    SPLITTER_V_STYLE, SPLITTER_H_STYLE,
    SEGMENTED_CONTROL_BUTTON_STYLE, GROUP_LABEL_TEXT_STYLE,
    ACTION_BUTTON_PRIMARY_EMPHASIS_STYLE, ACTION_BUTTON_PRIMARY_STYLE, ACTION_BUTTON_PRIMARY_COMPACT_STYLE,
    ACTION_BUTTON_PRIMARY_LARGE_STYLE,
    ACTION_BUTTON_SECONDARY_STYLE, ACTION_BUTTON_SECONDARY_LARGE_STYLE,
    TOGGLE_BUTTON_INACTIVE_STYLE, TOGGLE_BUTTON_INACTIVE_COMPACT_STYLE,
    PRIORITY_TABLE_STYLE, PRIORITY_COMBO_STYLE,
    _SEG_BTN_STYLE, _GROUP_LABEL_STYLE,
    _INTERACTIVE_BTN_ACTIVE, _INTERACTIVE_BTN_ON, _INTERACTIVE_BTN_ON_SM,
    _INTERACTIVE_BTN_LG,
    _DIM_BTN, _DIM_BTN_LG,
    _TOGGLE_OFF_BTN, _TOGGLE_OFF_BTN_SM,
    _PRIORITY_TABLE_STYLE, _PRIORITY_COMBO_STYLE,
)

from .columns import (
    COL_NAME, COL_LOC, COL_INJ,
    _STAT_COL_NAMES, _COL_STAT_START, _NUM_STAT_COLS,
    _SCORE_COLS, _COL_SCORE_START, COL_SEP1, COL_SCORE,
    COL_CW_SECTION_START,
    _ALL_HEADERS, _SEP_COLS, _SEP_WIDTH, _SEP_MIN_WIDTH,
    _NEUTRAL_VALUE_CHIP_COLS,
    _LOVE_SCORE_COLS, _HATE_SCORE_COLS, _RELATIONSHIP_SCORE_COLS,
    _SINGLE_VALUE_CENTER_SCORE_COLS, _MULTI_VALUE_LEFT_SCORE_COLS,
    _CHIP_ROLE, _SCORE_SECONDARY_ROLE, _HEATMAP_ROLE,
    _TRAIT_NAME_ROLE, _TRAIT_SUMMARY_ROLE,
    _ROOM_STYLE, INJURY_STAT_NAMES, _INJ_SHORT,
    _EMOJI_SCOPE, _EMOJI_ROOM,
)

_NUM_PROFILES = 5
